# Configuración del Servidor FinTech Andina

server {
    # 1. Nginx escucha en el puerto 80 (Tráfico web estándar)
    listen 80;
    server_name api.fintechandina.com;

    # 2. Servir Archivos Estáticos Directamente
    location /static/ {
        alias /var/www/fintechandina/static/;
        # Nginx despachará cualquier imagen o CSS directamente desde esta ruta
    }

    # 3. Proxy Inverso (Reverse Proxy) hacia Gunicorn
    location / {
        # Redirige el tráfico al puerto 8000 (el puerto interno de Gunicorn)
        proxy_pass http://127.0.0.1:8000;
        
        # Pasamos los encabezados originales para no perder la IP del cliente real
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}