# Definición del clúster de servidores backend (Gunicorn)
upstream backend_flask {
    server 127.0.0.1:8000 fail_timeout=0;
}

server {
    listen 80 deferred;
    server_name api.fintechandina.com;

    # Optimización: Compresión Gzip para respuestas JSON más rápidas
    gzip on;
    gzip_types application/json;

    # Seguridad: Ocultar versión de Nginx
    server_tokens off;

    # Despacho de estáticos por Nginx (Alivia a Python)
    location /static/ {
        alias /var/www/fintechandina/static/;
        expires 30d; # Caché de navegador para estáticos
    }

    # Proxy Inverso hacia Gunicorn
    location /api/ {
        proxy_pass http://backend_flask;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeouts para evitar que procesos largos bloqueen Nginx
        proxy_read_timeout 60s;
    }
}